Fetch SPIFFE identity in GitHub Actions pipeline
Added steps to fetch SPIFFE identity in the pipeline.

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -54,6 +54,7 @@ jobs:
       options: --user root
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock
+        - /opt/spire/sockets:/opt/spire/sockets
 
     steps:
       - name: Check current user
@@ -81,6 +82,24 @@ jobs:
       - name: Log in to Azure Container Registry
         shell: bash
         run: az acr login --name "${{ vars.ACR_NAME }}"
+
+      - name: Fetch SPIFFE identity
+        id: spiffe
+        run: |
+          spire-agent api fetch x509 \
+           -socketPath /opt/spire/sockets/agent.sock > svid.txt
+          cat svid.txt
+
+          SPIFFE_ID=$(grep -o 'spiffe://[^ ]*' svid.txt | head -1)
+          if [ -z "$SPIFFE_ID" ]; then
+            echo "Failed to fetch SPIFFE ID"
+            exit 1
+          fi
+
+          echo "Builder SPIFFE ID: $SPIFFE_ID"
+          echo "builder_spiffe_id=$SPIFFE_ID" >> "$GITHUB_OUTPUT"
+          echo "BUILDER_SPIFFE_ID=$SPIFFE_ID" >> "$GITHUB_ENV"
+          
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v4
@@ -138,9 +157,11 @@ jobs:
             --arg repo "git+https://github.com/${{ github.repository }}" \
             --arg sha "${{ github.sha }}" \
             --arg run_id "${{ github.run_id }}" \
+            --arg spiffe_id "${BUILDER_SPIFFE_ID}" \
             '{
               builder: {
-                id: "github-actions-self-hosted-azure-runner"
+                #id: "github-actions-self-hosted-azure-runner"
+                id: $spiffe_id
               },
               buildType: "https://github.com/Attestations/GitHubActionsWorkflow",
               invocation: {
